export interface District {
  name: string
  nameHindi: string
  nameOdia: string
  lat: number
  lon: number
  soilData: {
    type: string
    typeHindi: string
    typeOdia: string
    ph: string
    organicCarbon: string
    nitrogen: string
    phosphorus: string
    potassium: string
    suitableCrops: string[]
    suitableCropsHindi: string[]
    suitableCropsOdia: string[]
    recommendations: string
    recommendationsHindi: string
    recommendationsOdia: string
  }
}

export const odishaDistricts: District[] = [
  {
    name: "Angul",
    nameHindi: "अंगुल",
    nameOdia: "ଅନୁଗୁଲ",
    lat: 20.84,
    lon: 85.1,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Pulses", "Oilseeds", "Vegetables"],
      suitableCropsHindi: ["चावल", "दालें", "तिलहन", "सब्जियां"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ତେଲ ବିହନ", "ପନିପରିବା"],
      recommendations: "Apply lime to increase pH. Use organic manure. Implement soil conservation measures.",
      recommendationsHindi: "पीएच बढ़ाने के लिए चूना लगाएं। जैविक खाद का उपयोग करें। मृदा संरक्षण उपाय लागू करें।",
      recommendationsOdia: "pH ବୃଦ୍ଧି ପାଇଁ ଚୂନ ପ୍ରୟୋଗ କରନ୍ତୁ। ଜୈବିକ ଖତ ବ୍ୟବହାର କରନ୍ତୁ। ମାଟି ସଂରକ୍ଷଣ ପଦକ୍ଷେପ କାର୍ଯ୍ୟକାରୀ କରନ୍ତୁ।",
    },
  },
  {
    name: "Balangir",
    nameHindi: "बलांगीर",
    nameOdia: "ବଲାଙ୍ଗୀର",
    lat: 20.71,
    lon: 83.49,
    soilData: {
      type: "Red & Yellow Soil",
      typeHindi: "लाल और पीली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ହଳଦିଆ ମାଟି",
      ph: "5.8-6.8",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Medium",
      phosphorus: "Low to Medium",
      potassium: "Medium",
      suitableCrops: ["Rice", "Maize", "Pulses", "Cotton"],
      suitableCropsHindi: ["चावल", "मक्का", "दालें", "कपास"],
      suitableCropsOdia: ["ଚାଉଳ", "ମକା", "ଡାଲି", "କପା"],
      recommendations: "Regular application of FYM. Balanced fertilizer use. Crop rotation recommended.",
      recommendationsHindi: "एफवाईएम का नियमित अनुप्रयोग। संतुलित उर्वरक उपयोग। फसल चक्र की सिफारिश की जाती है।",
      recommendationsOdia: "FYM ର ନିୟମିତ ପ୍ରୟୋଗ। ସନ୍ତୁଳିତ ସାର ବ୍ୟବହାର। ଫସଲ ଚକ୍ର ସୁପାରିଶ କରାଯାଏ।",
    },
  },
  {
    name: "Balasore",
    nameHindi: "बालासोर",
    nameOdia: "ବାଲେଶ୍ୱର",
    lat: 21.49,
    lon: 86.93,
    soilData: {
      type: "Alluvial & Coastal Soil",
      typeHindi: "जलोढ़ और तटीय मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଉପକୂଳ ମାଟି",
      ph: "6.5-7.5",
      organicCarbon: "0.6-0.9%",
      nitrogen: "Medium to High",
      phosphorus: "Medium",
      potassium: "High",
      suitableCrops: ["Rice", "Vegetables", "Coconut", "Betel Vine"],
      suitableCropsHindi: ["चावल", "सब्जियां", "नारियल", "पान"],
      suitableCropsOdia: ["ଚାଉଳ", "ପନିପରିବା", "ନଡ଼ିଆ", "ପାନ"],
      recommendations: "Good for intensive cultivation. Ensure proper drainage. Salt-tolerant crops in coastal areas.",
      recommendationsHindi: "गहन खेती के लिए अच्छा। उचित जल निकासी सुनिश्चित करें। तटीय क्षेत्रों में नमक-सहिष्णु फसलें।",
      recommendationsOdia: "ଗଭୀର ଚାଷ ପାଇଁ ଭଲ। ଉପଯୁକ୍ତ ଜଳ ନିଷ୍କାସନ ସୁନିଶ୍ଚିତ କରନ୍ତୁ। ଉପକୂଳ ଅଞ୍ଚଳରେ ଲୁଣ-ସହନଶୀଳ ଫସଲ।",
    },
  },
  {
    name: "Bargarh",
    nameHindi: "बारगढ़",
    nameOdia: "ବରଗଡ଼",
    lat: 21.33,
    lon: 83.62,
    soilData: {
      type: "Red & Black Soil",
      typeHindi: "लाल और काली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ କଳା ମାଟି",
      ph: "6.0-7.0",
      organicCarbon: "0.5-0.8%",
      nitrogen: "Medium",
      phosphorus: "Medium",
      potassium: "Medium to High",
      suitableCrops: ["Rice", "Wheat", "Pulses", "Sugarcane"],
      suitableCropsHindi: ["चावल", "गेहूं", "दालें", "गन्ना"],
      suitableCropsOdia: ["ଚାଉଳ", "ଗହମ", "ଡାଲି", "ଆଖୁ"],
      recommendations: "Excellent for paddy cultivation. Use balanced NPK fertilizers. Maintain soil moisture.",
      recommendationsHindi: "धान की खेती के लिए उत्कृष्ट। संतुलित एनपीके उर्वरकों का उपयोग करें। मिट्टी की नमी बनाए रखें।",
      recommendationsOdia: "ଧାନ ଚାଷ ପାଇଁ ଉତ୍କୃଷ୍ଟ। ସନ୍ତୁଳିତ NPK ସାର ବ୍ୟବହାର କରନ୍ତୁ। ମାଟିର ଆର୍ଦ୍ରତା ବଜାୟ ରଖନ୍ତୁ।",
    },
  },
  {
    name: "Bhadrak",
    nameHindi: "भद्रक",
    nameOdia: "ଭଦ୍ରକ",
    lat: 21.05,
    lon: 86.5,
    soilData: {
      type: "Alluvial Soil",
      typeHindi: "जलोढ़ मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ମାଟି",
      ph: "6.8-7.5",
      organicCarbon: "0.7-1.0%",
      nitrogen: "High",
      phosphorus: "Medium to High",
      potassium: "High",
      suitableCrops: ["Rice", "Jute", "Vegetables", "Pulses"],
      suitableCropsHindi: ["चावल", "जूट", "सब्जियां", "दालें"],
      suitableCropsOdia: ["ଚାଉଳ", "ପାଟ", "ପନିପରିବା", "ଡାଲି"],
      recommendations: "Highly fertile soil. Suitable for multiple cropping. Ensure proper water management.",
      recommendationsHindi: "अत्यधिक उपजाऊ मिट्टी। बहु फसल के लिए उपयुक्त। उचित जल प्रबंधन सुनिश्चित करें।",
      recommendationsOdia: "ଅତ୍ୟଧିକ ଉର୍ବର ମାଟି। ବହୁ ଫସଲ ପାଇଁ ଉପଯୁକ୍ତ। ଉପଯୁକ୍ତ ଜଳ ପରିଚାଳନା ସୁନିଶ୍ଚିତ କରନ୍ତୁ।",
    },
  },
  {
    name: "Boudh",
    nameHindi: "बौध",
    nameOdia: "ବୌଦ୍ଧ",
    lat: 20.84,
    lon: 84.33,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Pulses", "Millets", "Oilseeds"],
      suitableCropsHindi: ["चावल", "दालें", "बाजरा", "तिलहन"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ମିଲେଟ", "ତେଲ ବିହନ"],
      recommendations: "Apply lime for pH correction. Use green manure. Implement contour farming.",
      recommendationsHindi: "पीएच सुधार के लिए चूना लगाएं। हरी खाद का उपयोग करें। समोच्च खेती लागू करें।",
      recommendationsOdia: "pH ସଂଶୋଧନ ପାଇଁ ଚୂନ ପ୍ରୟୋଗ କରନ୍ତୁ। ସବୁଜ ଖତ ବ୍ୟବହାର କରନ୍ତୁ। କଣ୍ଟୁର ଚାଷ କାର୍ଯ୍ୟକାରୀ କରନ୍ତୁ।",
    },
  },
  {
    name: "Cuttack",
    nameHindi: "कटक",
    nameOdia: "କଟକ",
    lat: 20.46,
    lon: 85.88,
    soilData: {
      type: "Alluvial Soil",
      typeHindi: "जलोढ़ मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ମାଟି",
      ph: "6.5-7.5",
      organicCarbon: "0.8-1.2%",
      nitrogen: "High",
      phosphorus: "High",
      potassium: "High",
      suitableCrops: ["Rice", "Vegetables", "Sugarcane", "Banana"],
      suitableCropsHindi: ["चावल", "सब्जियां", "गन्ना", "केला"],
      suitableCropsOdia: ["ଚାଉଳ", "ପନିପରିବା", "ଆଖୁ", "କଦଳୀ"],
      recommendations: "Excellent fertility. Ideal for intensive farming. Practice crop diversification.",
      recommendationsHindi: "उत्कृष्ट उर्वरता। गहन खेती के लिए आदर्श। फसल विविधीकरण का अभ्यास करें।",
      recommendationsOdia: "ଉତ୍କୃଷ୍ଟ ଉର୍ବରତା। ଗଭୀର ଚାଷ ପାଇଁ ଆଦର୍ଶ। ଫସଲ ବିବିଧୀକରଣ ଅଭ୍ୟାସ କରନ୍ତୁ।",
    },
  },
  {
    name: "Deogarh",
    nameHindi: "देवगढ़",
    nameOdia: "ଦେବଗଡ଼",
    lat: 21.54,
    lon: 84.73,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Turmeric"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "हल्दी"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "ହଳଦୀ"],
      recommendations: "Soil enrichment needed. Use organic matter. Terrace farming recommended.",
      recommendationsHindi: "मिट्टी संवर्धन की आवश्यकता। जैविक पदार्थ का उपयोग करें। सीढ़ीदार खेती की सिफारिश की जाती है।",
      recommendationsOdia: "ମାଟି ସମୃଦ୍ଧି ଆବଶ୍ୟକ। ଜୈବିକ ପଦାର୍ଥ ବ୍ୟବହାର କରନ୍ତୁ। ଟେରେସ ଚାଷ ସୁପାରିଶ କରାଯାଏ।",
    },
  },
  {
    name: "Dhenkanal",
    nameHindi: "ढेंकनाल",
    nameOdia: "ଢେଙ୍କାନାଳ",
    lat: 20.66,
    lon: 85.6,
    soilData: {
      type: "Red & Mixed Soil",
      typeHindi: "लाल और मिश्रित मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ମିଶ୍ରିତ ମାଟି",
      ph: "5.8-6.8",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Medium",
      phosphorus: "Low to Medium",
      potassium: "Medium",
      suitableCrops: ["Rice", "Pulses", "Vegetables", "Cashew"],
      suitableCropsHindi: ["चावल", "दालें", "सब्जियां", "काजू"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ପନିପରିବା", "କାଜୁ"],
      recommendations: "Moderate fertility. Regular manuring required. Soil conservation practices essential.",
      recommendationsHindi: "मध्यम उर्वरता। नियमित खाद की आवश्यकता। मृदा संरक्षण प्रथाएं आवश्यक।",
      recommendationsOdia: "ମଧ୍ୟମ ଉର୍ବରତା। ନିୟମିତ ଖତ ଆବଶ୍ୟକ। ମାଟି ସଂରକ୍ଷଣ ଅଭ୍ୟାସ ଅତ୍ୟାବଶ୍ୟକ।",
    },
  },
  {
    name: "Gajapati",
    nameHindi: "गजपति",
    nameOdia: "ଗଜପତି",
    lat: 19.39,
    lon: 84.13,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.0-6.0",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low",
      phosphorus: "Low",
      potassium: "Low to Medium",
      suitableCrops: ["Rice", "Millets", "Turmeric", "Cashew"],
      suitableCropsHindi: ["चावल", "बाजरा", "हल्दी", "काजू"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ହଳଦୀ", "କାଜୁ"],
      recommendations: "Acidic soil needs lime. Organic farming suitable. Horticulture crops recommended.",
      recommendationsHindi: "अम्लीय मिट्टी को चूने की आवश्यकता। जैविक खेती उपयुक्त। बागवानी फसलों की सिफारिश की जाती है।",
      recommendationsOdia: "ଅମ୍ଳୀୟ ମାଟିକୁ ଚୂନ ଆବଶ୍ୟକ। ଜୈବିକ ଚାଷ ଉପଯୁକ୍ତ। ଉଦ୍ୟାନ କୃଷି ଫସଲ ସୁପାରିଶ କରାଯାଏ।",
    },
  },
  {
    name: "Ganjam",
    nameHindi: "गंजम",
    nameOdia: "ଗଞ୍ଜାମ",
    lat: 19.39,
    lon: 84.97,
    soilData: {
      type: "Alluvial & Coastal Soil",
      typeHindi: "जलोढ़ और तटीय मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଉପକୂଳ ମାଟି",
      ph: "6.0-7.0",
      organicCarbon: "0.6-0.8%",
      nitrogen: "Medium to High",
      phosphorus: "Medium",
      potassium: "Medium to High",
      suitableCrops: ["Rice", "Pulses", "Cashew", "Coconut"],
      suitableCropsHindi: ["चावल", "दालें", "काजू", "नारियल"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "କାଜୁ", "ନଡ଼ିଆ"],
      recommendations: "Good for diverse crops. Coastal areas need salinity management. Plantation crops suitable.",
      recommendationsHindi: "विविध फसलों के लिए अच्छा। तटीय क्षेत्रों को लवणता प्रबंधन की आवश्यकता। वृक्षारोपण फसलें उपयुक्त।",
      recommendationsOdia: "ବିବିଧ ଫସଲ ପାଇଁ ଭଲ। ଉପକୂଳ ଅଞ୍ଚଳକୁ ଲୁଣିଆ ପରିଚାଳନା ଆବଶ୍ୟକ। ବୃକ୍ଷରୋପଣ ଫସଲ ଉପଯୁକ୍ତ।",
    },
  },
  {
    name: "Jagatsinghpur",
    nameHindi: "जगतसिंहपुर",
    nameOdia: "ଯାଜପୁର",
    lat: 20.25,
    lon: 86.17,
    soilData: {
      type: "Alluvial & Coastal Soil",
      typeHindi: "जलोढ़ और तटीय मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଉପକୂଳ ମାଟି",
      ph: "6.5-7.5",
      organicCarbon: "0.7-1.0%",
      nitrogen: "High",
      phosphorus: "Medium to High",
      potassium: "High",
      suitableCrops: ["Rice", "Vegetables", "Betel Vine", "Coconut"],
      suitableCropsHindi: ["चावल", "सब्जियां", "पान", "नारियल"],
      suitableCropsOdia: ["ଚାଉଳ", "ପନିପରିବା", "ପାନ", "ନଡ଼ିଆ"],
      recommendations: "Highly fertile deltaic soil. Excellent for paddy. Manage waterlogging in monsoon.",
      recommendationsHindi: "अत्यधिक उपजाऊ डेल्टाई मिट्टी। धान के लिए उत्कृष्ट। मानसून में जलभराव का प्रबंधन करें।",
      recommendationsOdia: "ଅତ୍ୟଧିକ ଉର୍ବର ଡେଲ୍ଟା ମାଟି। ଧାନ ପାଇଁ ଉତ୍କୃଷ୍ଟ। ମୌସୁମୀରେ ଜଳ ଜମା ପରିଚାଳନା କରନ୍ତୁ।",
    },
  },
  {
    name: "Jajpur",
    nameHindi: "जाजपुर",
    nameOdia: "ଯାଜପୁର",
    lat: 20.84,
    lon: 86.33,
    soilData: {
      type: "Alluvial Soil",
      typeHindi: "जलोढ़ मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ମାଟି",
      ph: "6.5-7.5",
      organicCarbon: "0.7-0.9%",
      nitrogen: "Medium to High",
      phosphorus: "Medium",
      potassium: "High",
      suitableCrops: ["Rice", "Vegetables", "Sugarcane", "Pulses"],
      suitableCropsHindi: ["चावल", "सब्जियां", "गन्ना", "दालें"],
      suitableCropsOdia: ["ଚାଉଳ", "ପନିପରିବା", "ଆଖୁ", "ଡାଲି"],
      recommendations:
        "Fertile soil suitable for intensive cultivation. Good water availability. Practice crop rotation.",
      recommendationsHindi: "गहन खेती के लिए उपजाऊ मिट्टी उपयुक्त। अच्छी जल उपलब्धता। फसल चक्र का अभ्यास करें।",
      recommendationsOdia: "ଗଭୀର ଚାଷ ପାଇଁ ଉର୍ବର ମାଟି ଉପଯୁକ୍ତ। ଭଲ ଜଳ ଉପଲବ୍ଧତା। ଫସଲ ଚକ୍ର ଅଭ୍ୟାସ କରନ୍ତୁ।",
    },
  },
  {
    name: "Jharsuguda",
    nameHindi: "झारसुगुड़ा",
    nameOdia: "ଝାରସୁଗୁଡ଼ା",
    lat: 21.85,
    lon: 84.01,
    soilData: {
      type: "Red & Black Soil",
      typeHindi: "लाल और काली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ କଳା ମାଟି",
      ph: "6.0-7.0",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Medium",
      phosphorus: "Medium",
      potassium: "Medium",
      suitableCrops: ["Rice", "Pulses", "Oilseeds", "Vegetables"],
      suitableCropsHindi: ["चावल", "दालें", "तिलहन", "सब्जियां"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ତେଲ ବିହନ", "ପନିପରିବା"],
      recommendations: "Moderate fertility. Use balanced fertilizers. Implement water conservation.",
      recommendationsHindi: "मध्यम उर्वरता। संतुलित उर्वरकों का उपयोग करें। जल संरक्षण लागू करें।",
      recommendationsOdia: "ମଧ୍ୟମ ଉର୍ବରତା। ସନ୍ତୁଳିତ ସାର ବ୍ୟବହାର କରନ୍ତୁ। ଜଳ ସଂରକ୍ଷଣ କାର୍ଯ୍ୟକାରୀ କରନ୍ତୁ।",
    },
  },
  {
    name: "Kalahandi",
    nameHindi: "कालाहांडी",
    nameOdia: "କଳାହାଣ୍ଡି",
    lat: 19.91,
    lon: 83.16,
    soilData: {
      type: "Red & Yellow Soil",
      typeHindi: "लाल और पीली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ହଳଦିଆ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Turmeric"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "हल्दी"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "ହଳଦୀ"],
      recommendations: "Soil improvement needed. Use organic manure. Drought-resistant crops suitable.",
      recommendationsHindi: "मिट्टी सुधार की आवश्यकता। जैविक खाद का उपयोग करें। सूखा प्रतिरोधी फसलें उपयुक्त।",
      recommendationsOdia: "ମାଟି ଉନ୍ନତି ଆବଶ୍ୟକ। ଜୈବିକ ଖତ ବ୍ୟବହାର କରନ୍ତୁ। ମରୁଡ଼ି ପ୍ରତିରୋଧୀ ଫସଲ ଉପଯୁକ୍ତ।",
    },
  },
  {
    name: "Kandhamal",
    nameHindi: "कंधमाल",
    nameOdia: "କନ୍ଧମାଳ",
    lat: 20.23,
    lon: 84.13,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.0-6.0",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Turmeric", "Ginger", "Millets", "Pulses"],
      suitableCropsHindi: ["हल्दी", "अदरक", "बाजरा", "दालें"],
      suitableCropsOdia: ["ହଳଦୀ", "ଆଦା", "ମିଲେଟ", "ଡାଲି"],
      recommendations: "Ideal for spice cultivation. Hilly terrain needs terracing. Organic farming recommended.",
      recommendationsHindi:
        "मसाला खेती के लिए आदर्श। पहाड़ी इलाके को सीढ़ीदार बनाने की आवश्यकता। जैविक खेती की सिफारिश की जाती है।",
      recommendationsOdia: "ମସଲା ଚାଷ ପାଇଁ ଆଦର୍ଶ। ପାହାଡ଼ିଆ ଅଞ୍ଚଳକୁ ଟେରେସିଂ ଆବଶ୍ୟକ। ଜୈବିକ ଚାଷ ସୁପାରିଶ କରାଯାଏ।",
    },
  },
  {
    name: "Kendrapara",
    nameHindi: "केंद्रपाड़ा",
    nameOdia: "କେନ୍ଦ୍ରାପଡ଼ା",
    lat: 20.5,
    lon: 86.42,
    soilData: {
      type: "Alluvial & Coastal Soil",
      typeHindi: "जलोढ़ और तटीय मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଉପକୂଳ ମାଟି",
      ph: "6.5-7.5",
      organicCarbon: "0.8-1.1%",
      nitrogen: "High",
      phosphorus: "High",
      potassium: "High",
      suitableCrops: ["Rice", "Betel Vine", "Vegetables", "Coconut"],
      suitableCropsHindi: ["चावल", "पान", "सब्जियां", "नारियल"],
      suitableCropsOdia: ["ଚାଉଳ", "ପାନ", "ପନିପରିବା", "ନଡ଼ିଆ"],
      recommendations: "Excellent for paddy. Manage salinity in coastal areas. Good for betel vine cultivation.",
      recommendationsHindi: "धान के लिए उत्कृष्ट। तटीय क्षेत्रों में लवणता का प्रबंधन करें। पान की खेती के लिए अच्छा।",
      recommendationsOdia: "ଧାନ ପାଇଁ ଉତ୍କୃଷ୍ଟ। ଉପକୂଳ ଅଞ୍ଚଳରେ ଲୁଣିଆ ପରିଚାଳନା କରନ୍ତୁ। ପାନ ଚାଷ ପାଇଁ ଭଲ।",
    },
  },
  {
    name: "Kendujhar",
    nameHindi: "केंदुझर",
    nameOdia: "କେନ୍ଦୁଝର",
    lat: 21.63,
    lon: 85.58,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Cashew"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "काजू"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "କାଜୁ"],
      recommendations: "Soil enrichment essential. Use lime and organic matter. Suitable for horticulture.",
      recommendationsHindi: "मिट्टी संवर्धन आवश्यक। चूना और जैविक पदार्थ का उपयोग करें। बागवानी के लिए उपयुक्त।",
      recommendationsOdia: "ମାଟି ସମୃଦ୍ଧି ଅତ୍ୟାବଶ୍ୟକ। ଚୂନ ଏବଂ ଜୈବିକ ପଦାର୍ଥ ବ୍ୟବହାର କରନ୍ତୁ। ଉଦ୍ୟାନ କୃଷି ପାଇଁ ଉପଯୁକ୍ତ।",
    },
  },
  {
    name: "Khordha",
    nameHindi: "खोरधा",
    nameOdia: "ଖୋର୍ଦ୍ଧା",
    lat: 20.18,
    lon: 85.62,
    soilData: {
      type: "Alluvial & Red Soil",
      typeHindi: "जलोढ़ और लाल मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଲାଲ ମାଟି",
      ph: "6.0-7.0",
      organicCarbon: "0.6-0.8%",
      nitrogen: "Medium to High",
      phosphorus: "Medium",
      potassium: "Medium to High",
      suitableCrops: ["Rice", "Vegetables", "Pulses", "Flowers"],
      suitableCropsHindi: ["चावल", "सब्जियां", "दालें", "फूल"],
      suitableCropsOdia: ["ଚାଉଳ", "ପନିପରିବା", "ଡାଲି", "ଫୁଲ"],
      recommendations: "Good for diverse crops. Suitable for commercial farming. Practice integrated farming.",
      recommendationsHindi: "विविध फसलों के लिए अच्छा। वाणिज्यिक खेती के लिए उपयुक्त। एकीकृत खेती का अभ्यास करें।",
      recommendationsOdia: "ବିବିଧ ଫସଲ ପାଇଁ ଭଲ। ବାଣିଜ୍ୟିକ ଚାଷ ପାଇଁ ଉପଯୁକ୍ତ। ଏକୀକୃତ ଚାଷ ଅଭ୍ୟାସ କରନ୍ତୁ।",
    },
  },
  {
    name: "Koraput",
    nameHindi: "कोरापुट",
    nameOdia: "କୋରାପୁଟ",
    lat: 18.81,
    lon: 82.71,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.0-6.0",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Coffee", "Spices"],
      suitableCropsHindi: ["चावल", "बाजरा", "कॉफी", "मसाले"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "କଫି", "ମସଲା"],
      recommendations: "Hilly terrain suitable for plantation crops. Organic farming ideal. Soil conservation crucial.",
      recommendationsHindi: "पहाड़ी इलाका वृक्षारोपण फसलों के लिए उपयुक्त। जैविक खेती आदर्श। मृदा संरक्षण महत्वपूर्ण।",
      recommendationsOdia: "ପାହାଡ଼ିଆ ଅଞ୍ଚଳ ବୃକ୍ଷରୋପଣ ଫସଲ ପାଇଁ ଉପଯୁକ୍ତ। ଜୈବିକ ଚାଷ ଆଦର୍ଶ। ମାଟି ସଂରକ୍ଷଣ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ।",
    },
  },
  {
    name: "Malkangiri",
    nameHindi: "मलकानगिरि",
    nameOdia: "ମାଲକାନଗିରି",
    lat: 18.35,
    lon: 81.89,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.0-6.0",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low",
      phosphorus: "Low",
      potassium: "Low to Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Cashew"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "काजू"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "କାଜୁ"],
      recommendations: "Soil improvement needed. Use green manure. Suitable for tribal farming practices.",
      recommendationsHindi: "मिट्टी सुधार की आवश्यकता। हरी खाद का उपयोग करें। आदिवासी खेती प्रथाओं के लिए उपयुक्त।",
      recommendationsOdia: "ମାଟି ଉନ୍ନତି ଆବଶ୍ୟକ। ସବୁଜ ଖତ ବ୍ୟବହାର କରନ୍ତୁ। ଆଦିବାସୀ ଚାଷ ଅଭ୍ୟାସ ପାଇଁ ଉପଯୁକ୍ତ।",
    },
  },
  {
    name: "Mayurbhanj",
    nameHindi: "मयूरभंज",
    nameOdia: "ମୟୂରଭଞ୍ଜ",
    lat: 21.93,
    lon: 86.73,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Cashew"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "काजू"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "କାଜୁ"],
      recommendations: "Use lime for pH correction. Organic farming suitable. Good for horticulture crops.",
      recommendationsHindi: "पीएच सुधार के लिए चूना का उपयोग करें। जैविक खेती उपयुक्त। बागवानी फसलों के लिए अच्छा।",
      recommendationsOdia: "pH ସଂଶୋଧନ ପାଇଁ ଚୂନ ବ୍ୟବହାର କରନ୍ତୁ। ଜୈବିକ ଚାଷ ଉପଯୁକ୍ତ। ଉଦ୍ୟାନ କୃଷି ଫସଲ ପାଇଁ ଭଲ।",
    },
  },
  {
    name: "Nabarangpur",
    nameHindi: "नबरंगपुर",
    nameOdia: "ନବରଙ୍ଗପୁର",
    lat: 19.23,
    lon: 82.55,
    soilData: {
      type: "Red & Yellow Soil",
      typeHindi: "लाल और पीली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ହଳଦିଆ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Turmeric"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "हल्दी"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "ହଳଦୀ"],
      recommendations: "Soil enrichment required. Use organic matter. Suitable for rainfed agriculture.",
      recommendationsHindi: "मिट्टी संवर्धन की आवश्यकता। जैविक पदार्थ का उपयोग करें। वर्षा आधारित कृषि के लिए उपयुक्त।",
      recommendationsOdia: "ମାଟି ସମୃଦ୍ଧି ଆବଶ୍ୟକ। ଜୈବିକ ପଦାର୍ଥ ବ୍ୟବହାର କରନ୍ତୁ। ବର୍ଷା ଆଧାରିତ କୃଷି ପାଇଁ ଉପଯୁକ୍ତ।",
    },
  },
  {
    name: "Nayagarh",
    nameHindi: "नयागढ़",
    nameOdia: "ନୟାଗଡ଼",
    lat: 20.13,
    lon: 85.1,
    soilData: {
      type: "Red & Mixed Soil",
      typeHindi: "लाल और मिश्रित मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ମିଶ୍ରିତ ମାଟି",
      ph: "5.8-6.8",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Medium",
      phosphorus: "Low to Medium",
      potassium: "Medium",
      suitableCrops: ["Rice", "Pulses", "Vegetables", "Turmeric"],
      suitableCropsHindi: ["चावल", "दालें", "सब्जियां", "हल्दी"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ପନିପରିବା", "ହଳଦୀ"],
      recommendations: "Moderate fertility. Regular manuring needed. Good for mixed cropping.",
      recommendationsHindi: "मध्यम उर्वरता। नियमित खाद की आवश्यकता। मिश्रित फसल के लिए अच्छा।",
      recommendationsOdia: "ମଧ୍ୟମ ଉର୍ବରତା। ନିୟମିତ ଖତ ଆବଶ୍ୟକ। ମିଶ୍ରିତ ଫସଲ ପାଇଁ ଭଲ।",
    },
  },
  {
    name: "Nuapada",
    nameHindi: "नुआपाड़ा",
    nameOdia: "ନୂଆପଡ଼ା",
    lat: 20.76,
    lon: 82.53,
    soilData: {
      type: "Red & Yellow Soil",
      typeHindi: "लाल और पीली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ହଳଦିଆ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.4-0.6%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Oilseeds"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "तिलहन"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "ତେଲ ବିହନ"],
      recommendations: "Soil improvement essential. Use organic amendments. Drought-resistant varieties recommended.",
      recommendationsHindi: "मिट्टी सुधार आवश्यक। जैविक संशोधनों का उपयोग करें। सूखा प्रतिरोधी किस्मों की सिफारिश की जाती है।",
      recommendationsOdia: "ମାଟି ଉନ୍ନତି ଅତ୍ୟାବଶ୍ୟକ। ଜୈବିକ ସଂଶୋଧନ ବ୍ୟବହାର କରନ୍ତୁ। ମରୁଡ଼ି ପ୍ରତିରୋଧୀ କିସମ ସୁପାରିଶ କରାଯାଏ।",
    },
  },
  {
    name: "Puri",
    nameHindi: "पुरी",
    nameOdia: "ପୁରୀ",
    lat: 19.81,
    lon: 85.83,
    soilData: {
      type: "Alluvial & Coastal Soil",
      typeHindi: "जलोढ़ और तटीय मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଉପକୂଳ ମାଟି",
      ph: "6.5-7.5",
      organicCarbon: "0.7-1.0%",
      nitrogen: "Medium to High",
      phosphorus: "Medium",
      potassium: "High",
      suitableCrops: ["Rice", "Vegetables", "Coconut", "Betel Vine"],
      suitableCropsHindi: ["चावल", "सब्जियां", "नारियल", "पान"],
      suitableCropsOdia: ["ଚାଉଳ", "ପନିପରିବା", "ନଡ଼ିଆ", "ପାନ"],
      recommendations: "Fertile coastal soil. Manage salinity. Excellent for paddy and coconut.",
      recommendationsHindi: "उपजाऊ तटीय मिट्टी। लवणता का प्रबंधन करें। धान और नारियल के लिए उत्कृष्ट।",
      recommendationsOdia: "ଉର୍ବର ଉପକୂଳ ମାଟି। ଲୁଣିଆ ପରିଚାଳନା କରନ୍ତୁ। ଧାନ ଏବଂ ନଡ଼ିଆ ପାଇଁ ଉତ୍କୃଷ୍ଟ।",
    },
  },
  {
    name: "Rayagada",
    nameHindi: "रायगडा",
    nameOdia: "ରାୟଗଡ଼",
    lat: 19.17,
    lon: 83.42,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.0-6.0",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Turmeric", "Coffee"],
      suitableCropsHindi: ["चावल", "बाजरा", "हल्दी", "कॉफी"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ହଳଦୀ", "କଫି"],
      recommendations: "Hilly terrain suitable for spices. Use organic farming. Terrace cultivation recommended.",
      recommendationsHindi: "पहाड़ी इलाका मसालों के लिए उपयुक्त। जैविक खेती का उपयोग करें। सीढ़ीदार खेती की सिफारिश की जाती है।",
      recommendationsOdia: "ପାହାଡ଼ିଆ ଅଞ୍ଚଳ ମସଲା ପାଇଁ ଉପଯୁକ୍ତ। ଜୈବିକ ଚାଷ ବ୍ୟବହାର କରନ୍ତୁ। ଟେରେସ ଚାଷ ସୁପାରିଶ କରାଯାଏ।",
    },
  },
  {
    name: "Sambalpur",
    nameHindi: "संबलपुर",
    nameOdia: "ସମ୍ବଲପୁର",
    lat: 21.47,
    lon: 83.97,
    soilData: {
      type: "Red & Black Soil",
      typeHindi: "लाल और काली मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ କଳା ମାଟି",
      ph: "6.0-7.0",
      organicCarbon: "0.6-0.8%",
      nitrogen: "Medium",
      phosphorus: "Medium",
      potassium: "Medium to High",
      suitableCrops: ["Rice", "Pulses", "Oilseeds", "Vegetables"],
      suitableCropsHindi: ["चावल", "दालें", "तिलहन", "सब्जियां"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ତେଲ ବିହନ", "ପନିପରିବା"],
      recommendations: "Good fertility. Suitable for diverse crops. Practice balanced fertilization.",
      recommendationsHindi: "अच्छी उर्वरता। विविध फसलों के लिए उपयुक्त। संतुलित उर्वरक का अभ्यास करें।",
      recommendationsOdia: "ଭଲ ଉର୍ବରତା। ବିବିଧ ଫସଲ ପାଇଁ ଉପଯୁକ୍ତ। ସନ୍ତୁଳିତ ସାର ଅଭ୍ୟାସ କରନ୍ତୁ।",
    },
  },
  {
    name: "Subarnapur",
    nameHindi: "सुबर्णपुर",
    nameOdia: "ସୁବର୍ଣ୍ଣପୁର",
    lat: 20.84,
    lon: 83.92,
    soilData: {
      type: "Alluvial & Red Soil",
      typeHindi: "जलोढ़ और लाल मिट्टी",
      typeOdia: "ଜଳୋଢ଼ ଏବଂ ଲାଲ ମାଟି",
      ph: "6.0-7.0",
      organicCarbon: "0.6-0.8%",
      nitrogen: "Medium to High",
      phosphorus: "Medium",
      potassium: "Medium to High",
      suitableCrops: ["Rice", "Pulses", "Vegetables", "Sugarcane"],
      suitableCropsHindi: ["चावल", "दालें", "सब्जियां", "गन्ना"],
      suitableCropsOdia: ["ଚାଉଳ", "ଡାଲି", "ପନିପରିବା", "ଆଖୁ"],
      recommendations: "Fertile soil. Good for intensive cultivation. Implement crop rotation.",
      recommendationsHindi: "उपजाऊ मिट्टी। गहन खेती के लिए अच्छा। फसल चक्र लागू करें।",
      recommendationsOdia: "ଉର୍ବର ମାଟି। ଗଭୀର ଚାଷ ପାଇଁ ଭଲ। ଫସଲ ଚକ୍ର କାର୍ଯ୍ୟକାରୀ କରନ୍ତୁ।",
    },
  },
  {
    name: "Sundargarh",
    nameHindi: "सुंदरगढ़",
    nameOdia: "ସୁନ୍ଦରଗଡ଼",
    lat: 22.12,
    lon: 84.03,
    soilData: {
      type: "Red & Laterite Soil",
      typeHindi: "लाल और लेटराइट मिट्टी",
      typeOdia: "ଲାଲ ଏବଂ ଲାଟେରାଇଟ ମାଟି",
      ph: "5.5-6.5",
      organicCarbon: "0.5-0.7%",
      nitrogen: "Low to Medium",
      phosphorus: "Low",
      potassium: "Medium",
      suitableCrops: ["Rice", "Millets", "Pulses", "Vegetables"],
      suitableCropsHindi: ["चावल", "बाजरा", "दालें", "सब्जियां"],
      suitableCropsOdia: ["ଚାଉଳ", "ମିଲେଟ", "ଡାଲି", "ପନିପରିବା"],
      recommendations: "Use lime for pH improvement. Apply organic manure. Soil conservation measures needed.",
      recommendationsHindi: "पीएच सुधार के लिए चूना का उपयोग करें। जैविक खाद लगाएं। मृदा संरक्षण उपायों की आवश्यकता।",
      recommendationsOdia: "pH ଉନ୍ନତି ପାଇଁ ଚୂନ ବ୍ୟବହାର କରନ୍ତୁ। ଜୈବିକ ଖତ ପ୍ରୟୋଗ କରନ୍ତୁ। ମାଟି ସଂରକ୍ଷଣ ପଦକ୍ଷେପ ଆବଶ୍ୟକ।",
    },
  },
]
